### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
[Fastlane](https://gitlab.com/-/snippets/1895688) structures as discussed in #1 (for hints on formatting the `full_description.txt`, please [see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane).

Related: #6 (F-Droid will ask for this).

### CODE REVIEW

**Comment by jroddev** [comment]
Thanks @IzzySoft

**Comment by IzzySoft** [comment]
Gladly – and thanks for merging! Updated the config here so changes to it will be pulled along with releases.

Btw: you might wish to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to [your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.jroddev.android_oss_release_tracker) from your Readme :wink:

**Comment by jroddev** [comment]
@IzzySoft . Added here: https://github.com/jroddev/android-oss-release-tracker/commit/770e986b62325a4ca6d39b74e052532f95b69f6c

**Comment by IzzySoft** [comment]
Thanks! :star_struck:

**Pull request merged**
